services:
  api:
    build:
      context: api/docker
      dockerfile: development/php/Dockerfile
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      PHP_IDE_CONFIG: serverName=LARAVEL_API
      DB_CONNECTION: pgsql
      DB_HOST: api-postgres
      DB_PORT: 5432
      DB_DATABASE: app
      DB_USERNAME: app
      DB_PASSWORD: secret
    ports:
      - "8001:8000"
    volumes:
      - ./api:/app
    depends_on:
      - api-postgres

  api-postgres:
    image: postgres:18.4-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - api-postgres:/var/lib/postgresql
    ports:
      - "54301:5432"

  api-postgres-test:
    image: postgres:18.4-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - api-postgres-test:/var/lib/postgresql
    ports:
      - "54302:5432"

volumes:
  api-postgres:
  api-postgres-test:
